const PDFDocument = require("pdfkit");

// Both functions return a Promise<Buffer> so callers can either send the PDF
// directly as a download response, or attach the same buffer to an email.

function generateReceiptPDF(invoice, patient) {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50 });
    const chunks = [];
    doc.on("data", (c) => chunks.push(c));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    doc.fontSize(20).fillColor("#0e7490").text("DentalCare Clinic", { align: "center" });
    doc.fontSize(12).fillColor("#64748b").text("Payment Receipt", { align: "center" });
    doc.moveDown(1.5);

    doc.fillColor("#1e293b").fontSize(11);
    doc.text(`Receipt Date: ${new Date(invoice.createdAt).toLocaleDateString()}`);
    doc.text(`Patient: ${patient.name}`);
    doc.text(`Phone: ${patient.phone}`);
    doc.moveDown();

    doc.fontSize(13).fillColor("#0e7490").text("Items", { underline: true });
    doc.moveDown(0.3);
    doc.fontSize(11).fillColor("#1e293b");
    invoice.items.forEach((item) => {
      doc.text(`${item.treatment}`, { continued: true });
      doc.text(`₹${item.cost}`, { align: "right" });
    });

    doc.moveDown();
    doc.moveTo(50, doc.y).lineTo(545, doc.y).strokeColor("#cbd5e1").stroke();
    doc.moveDown(0.5);

    doc.fontSize(11);
    doc.text(`Total Amount:`, { continued: true });
    doc.text(`₹${invoice.totalAmount}`, { align: "right" });
    doc.text(`Amount Paid:`, { continued: true });
    doc.text(`₹${invoice.paidAmount}`, { align: "right" });
    doc.text(`Balance Due:`, { continued: true });
    doc.text(`₹${invoice.totalAmount - invoice.paidAmount}`, { align: "right" });
    doc.moveDown();
    doc.fontSize(12).fillColor("#0e7490").text(`Status: ${invoice.status}`);

    doc.moveDown(2);
    doc.fontSize(9).fillColor("#94a3b8").text("Thank you for visiting DentalCare Clinic.", { align: "center" });

    doc.end();
  });
}

function generateMedicalReportPDF(record, patient) {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50 });
    const chunks = [];
    doc.on("data", (c) => chunks.push(c));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    doc.fontSize(20).fillColor("#0e7490").text("DentalCare Clinic", { align: "center" });
    doc.fontSize(12).fillColor("#64748b").text("Medical Report", { align: "center" });
    doc.moveDown(1.5);

    doc.fillColor("#1e293b").fontSize(11);
    doc.text(`Visit Date: ${new Date(record.visitDate).toLocaleDateString()}`);
    doc.text(`Patient: ${patient.name}`);
    doc.text(`Phone: ${patient.phone}`);
    doc.moveDown();

    const field = (label, value) => {
      doc.fontSize(12).fillColor("#0e7490").text(label);
      doc.fontSize(11).fillColor("#1e293b").text(value || "-");
      doc.moveDown(0.7);
    };

    field("Diagnosis", record.diagnosis);
    field("Treatment Done", record.treatmentDone);
    field("Prescription", record.prescription);
    field("Notes", record.notes);

    doc.moveDown(1.5);
    doc.fontSize(9).fillColor("#94a3b8").text("This report is generated by DentalCare Clinic's management system.", { align: "center" });

    doc.end();
  });
}

module.exports = { generateReceiptPDF, generateMedicalReportPDF };
